# Generated by Django 4.2.5 on 2023-09-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Service Title"),
                ),
                ("subtitle", models.CharField(max_length=200, verbose_name="subtitle")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "image",
                    models.ImageField(upload_to="services", verbose_name="image"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "ordering": ["-created"],
            },
        ),
    ]
